[tox]
envlist = test_ported_on_portedlib_py27, test_native_on_portedlib, test_ported_on_portedlib, test_ported_on_nativelib, test_native_on_nativelib

[testenv:test_ported_on_portedlib_py27]
basepython = python2.7
deps =
    typing==3.10.0
    typing-extensions==3.10.0
    dictproxyhack==1.1
    funcsigs==1.0.2
    unittest2==1.1.0
description = Run Python 2.7 tests on Python 2.7 with dataclasses backport
commands =
    python -m unittest2 tests/test_ported_on_portedlib.py

[testenv:test_native_on_portedlib]
basepython = python3.14
description = Run Python 3.14 tests on Python 3.14 with dataclasses backport
commands =
    python -m unittest tests/test_native_on_portedlib.py

[testenv:test_ported_on_portedlib]
basepython = python3.14
description = Run Python 2.7 tests on Python 3.14 with dataclasses backport
commands =
    python -m unittest tests/test_ported_on_portedlib.py

[testenv:test_ported_on_nativelib]
basepython = python3.14
description = Run Python 2.7 tests on Python 3.14 with native dataclasses
commands =
    python -m unittest tests/test_ported_on_nativelib.py

[testenv:test_native_on_nativelib]
basepython = python3.14
description = Run Python 3.14 tests on Python 3.14 with native dataclasses
commands =
    python -m unittest tests/test_native_on_nativelib.py
