[tox]
skipsdist = true
commands =
    pymanager install 2.7
    pymanager install 3.9
    pymanager install 3.14
envlist =
    py2-tests27-with-backport
    py3-tests27-with-original
    py3-tests314-with-original
    py3-tests314-with-backport
    py3-tests27-with-backport
allowlist_externals =
    pymanager

[testenv]
allowlist_externals =
    pymanager

deps =
    pytest
    six
    unittest2
    funcsigs
    dictproxyhack
    typing

[testenv:py2-tests27-with-backport]
basepython = python2.7
commands =
    unit2 discover tests.test_Dataclasses_py27

[testenv:py3-tests27-with-original]
basepython = python3.14
commands =
    python -m unittest discover tests.test_Dataclasses_py27_original_py3

[testenv:py3-tests314-with-original]
basepython = python3.14
commands =
    python -m unittest discover tests.test_Dataclasses_py314

[testenv:py3-tests314-with-backport]
basepython = python3.14
commands =
    python -m unittest discover tests.test_Dataclasses_py314_backport_py3

[testenv:py3-tests27-with-backport]
basepython = python3.14
commands =
    python -m unittest discover tests.test_Dataclasses_py27_backport_py3
