name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - dev
      - staging
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - python-version: "2.7"
            suffix: "2"
            os: ubuntu-latest
            container:
              image: coatldev/six:latest
              env:
                UV_PYTHON: '3.14'
          - python-version: "3.14"
            os: ubuntu-latest
            container: python:3.14
#          - python-version: "3.x"
#            os: ubuntu-latest
#            container: python:latest

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          python${{ matrix.suffix }} -m pip install --upgrade pip
          python${{ matrix.suffix }} -m pip install setuptools wheel

      - name: Build dev package
        if: matrix.suffix == ''
        run: |
          python${{ matrix.suffix }} setup.py sdist

      - name: Build package
        run: |
          python${{ matrix.suffix }} setup.py bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: py2dataclasses-py${{ matrix.python-version }}
          path: dist/*