name: Publish
permissions:
  contents: write
  discussions: write
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      ref:
        description: 'Release commit or tag'
        required: false
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ inputs.ref || github.sha }}
          path: dist

      - name: Install Twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine

      - name: Create release and upload assets
        if:  ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI }}
        run: |
          python -m twine upload dist/**/* --verbose