name: Test

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - python-version: "2.7"
            os: ubuntu-latest
            suffix: "2"
            container:
              image: coatldev/six:latest
            tox-env: "test_ported_on_portedlib_py27"
          - python-version: "3.14"
            os: ubuntu-latest
            container: python:3.14
            tox-env: "test_native_on_portedlib"
          - python-version: "3.14"
            os: ubuntu-latest
            container: python:3.14
            tox-env: "test_ported_on_portedlib"
          - python-version: "3.14"
            os: ubuntu-latest
            container: python:3.14
            tox-env: "test_ported_on_nativelib"
          - python-version: "3.14"
            os: ubuntu-latest
            container: python:3.14
            tox-env: "test_native_on_nativelib"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v5
      - name: Install deps
        run: apt-get install --yes gnupg2
      - name: Install tox
        run: python${{ matrix.suffix }} -m pip install tox
      - name: Run tox
        run: python${{ matrix.suffix }} -m tox -e ${{ matrix.tox-env }}
        continue-on-error: true
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.tox-env }}.xml
          name: ${{ matrix.tox-env }}
          flags: ${{ matrix.tox-env }}
          slug: nev3rfail/py2dataclasses
